// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Ismael Hamed")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.1.2.0")]
