// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompany("Ismael Hamed")]
[assembly: AssemblyCopyright("Copyright © 2015-2018 Ismael Hamed")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyVersion("1.3.5")]
[assembly: AssemblyFileVersion("1.3.5")]
