name: .NET

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches-ignore:
      - master
  pull_request:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'ismaelhamed/akka.persistence.oracle'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/

    - name: Build
      run: dotnet build --no-restore --configuration Release ./src

    - name: Test
      run: dotnet test --no-build --configuration Release --logger GitHubActions ./src