name: .NET

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: 
      - github-actions
  pull_request:
    branches: [ dev ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
    - name: Build
      run: dotnet build --no-restore  --configuration Release ./src
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal ./src